[workspace]
members = [
    "cmac",
    "daa",
    "hmac",
    "pmac",
]

[patch.crates-io]
digest = { git = "https://github.com/RustCrypto/traits" }
des = { git = "https://github.com/RustCrypto/block-ciphers" }
md-5 = { git = "https://github.com/RustCrypto/hashes" }
sha2 = { git = "https://github.com/RustCrypto/hashes" }
