[workspace]
members = [
    "cmac",
    "daa",
    "hmac",
    "pmac",
]

[patch.crates-io]
aes = { git = "https://github.com/RustCrypto/block-ciphers" }
block-cipher = { git = "https://github.com/RustCrypto/traits" }
crypto-mac = { git = "https://github.com/RustCrypto/traits" }
dbl = { git = "https://github.com/RustCrypto/utils" }
