[workspace]
members = [
    "cmac",
    "hmac",
]

[patch.crates-io]
block-cipher-trait = { git = "https://github.com/RustCrypto/traits" }
aesni = { git = "https://github.com/RustCrypto/block-ciphers" }
des = { git = "https://github.com/RustCrypto/block-ciphers" }
