[package]
name = "cmac"
version = "0.3.0-pre"
description = "Generic implementation of Cipher-based Message Authentication Code"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/cmac"
repository = "https://github.com/RustCrypto/MACs"
keywords = ["crypto", "mac", "cmac", "omac"]
categories = ["cryptography", "no-std"]
readme = "README.md"
edition = "2018"

[dependencies]
crypto-mac = "= 0.8.0-pre"
block-cipher = "= 0.7.0-pre"
dbl = "= 0.3.0-pre"

[dev-dependencies]
crypto-mac = { version = "= 0.8.0-pre", features = ["dev"] }
aes = "= 0.4.0-pre"
