[package]
name = "pmac"
version = "0.2.0"
description = "Generic implementation of Parallelizable Message Authentication Code"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/pmac"
repository = "https://github.com/RustCrypto/MACs"
keywords = ["crypto", "mac", "pmac"]
categories = ["cryptography", "no-std"]
readme = "README.md"

[dependencies]
crypto-mac = "0.7"
block-cipher-trait = "0.6"
dbl = "0.2"

[dev-dependencies]
crypto-mac = { version = "0.7", features = ["dev"] }
aes = "0.3"
