[package]
name = "pmac"
version = "0.2.0"
description = "Generic implementation of Parallelizable Message Authentication Code"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/pmac"
repository = "https://github.com/RustCrypto/MACs"
keywords = ["crypto", "mac", "pmac"]
categories = ["cryptography", "no-std"]
readme = "README.md"
edition = "2018"

[dependencies]
crypto-mac = "= 0.8.0-pre"
block-cipher = "0.7.0-pre"
dbl = "0.3.0-pre"

[dev-dependencies]
crypto-mac = { version = "0.8.0-pre", features = ["dev"] }
aes = "0.4.0-pre"
