[package]
name = "daa"
version = "0.2.0-pre"
description = "Implementation of Data Authentication Algorithm (DAA)"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/daa"
repository = "https://github.com/RustCrypto/MACs"
keywords = ["crypto", "mac", "daa", "fips"]
readme = "README.md"
edition = "2018"

[dependencies]
crypto-mac = "= 0.8.0-pre"
des = "= 0.4.0-pre"

[dev-dependencies]
crypto-mac = { version = "= 0.8.0-pre", features = ["dev"] }
